development:
  adapter: postgresql
  database: baby_steps_dev_database
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: baby_steps_test_database
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: baby_steps_production_database #rename this to whatever you want
  pool: 5
  timeout: 5000
